In [1]:
import numpy as np

1. Adjust your Gauss Elimination Python code to do partial pivoting before solving a system of equations
with possible division by zero. To check if your code works, solve the following system with your code and
with numpy.linalg.solve:

<center>
$x_1 − x_2 + x_3 = 2$ <br>
$−6x_1 + x_2 − x_3 = 3$ <br>
$3x_1 + x_2 + x_3 = 4$ <br>
</center>


In [2]:
a = np.array([[1,-1,1],[-6,1,-1],[3,1,1]], dtype=float)      # Variable matrix
b = np.array([[2],[3],[4]], dtype=float)                     # Constant vector
n = len(b)
x = np.zeros(n, float)
print('Matrix A: \n {0}'.format(a))
print('Matrix B: \n {0}'.format(b))

# The simplest way to revise the code is add the following lines
if np.abs(a[0,0]) < np.abs(a[1,0]):
    a[[0, 1]] = a[[1, 0]]       # this is how you swap two rows
    b[[0, 1]] = b[[1, 0]]       # this is how you swap two elements
elif np.abs(a[0,0]) < np.abs(a[2,0]):
    a[[0, 2]] = a[[2, 0]]
    b[[0, 2]] = b[[2, 0]]
    
print('Matrix A after partial pivoting: \n {0}'.format(a))
print('Matrix B after partial pivoting: \n {0}'.format(b))

# forward elimination
for k in range(n):                                     # for matrix a, for each orig row k, starting at top
    for i in range(k+1,n):                             # get the next row i, first column element
        factor = a[i,k]/a[k,k]                         # and use it to get the factor
        for j in range(k,n):                           # then for the elements in each column of next row i,
            a[i,j] = a[i,j] - a[k,j]*factor            # calculate original values of next row i minus orig row k times factor 
        b[i] = b[i] - b[k]*factor                      # for matrix b, original value at next row i minus orig row k times factor

print('Augmented matrix')
print(np.concatenate((a,b), axis=1))                   # display result after forward elimination

# back substitution
x[n-1] = b[n-1]/a[n-1,n-1]                            # get last value of solution matrix
print(x[n-1])

for i in range(n-2,-1,-1):                             # 
    Sum = b[i]
    for j in range(i+1, n):
        Sum = Sum - a[i,j]*x[j]
    x[i] = Sum/a[i,i]
    
print(x)

Matrix A: 
 [[ 1. -1.  1.]
 [-6.  1. -1.]
 [ 3.  1.  1.]]
Matrix B: 
 [[2.]
 [3.]
 [4.]]
Matrix A after partial pivoting: 
 [[-6.  1. -1.]
 [ 1. -1.  1.]
 [ 3.  1.  1.]]
Matrix B after partial pivoting: 
 [[3.]
 [2.]
 [4.]]
Augmented matrix
[[-6.          1.         -1.          3.        ]
 [ 0.         -0.83333333  0.83333333  2.5       ]
 [ 0.          0.          2.         10.        ]]
5.0
[-1.  2.  5.]


In [3]:
X_py = np.linalg.solve(a,b)
print(X_py)
# Check if solution is correct
np.allclose(np.dot(a,X_py), b) # True if arrays are element-wuse equal

[[-1.]
 [ 2.]
 [ 5.]]


True

2. Try solving the earlier example with your code, now with partial pivoting (30 pts.):
$$\begin{bmatrix} 25 & 5 & 1  ⁝ 106.8 \\ 64 & 8 & 1  ⁝ 177.2 \\ 144 & 12 & 1  ⁝ 279.2\end{bmatrix}$$

Do not forget to check your answers with numpy.linalg.solve

In [4]:
# I just copy pasted the cell above, with a and b revised

a = np.array([[25,5,1],[64,8,1],[144,12,1]], dtype=float)      # Variable matrix
b = np.array([[106.8],[177.2],[279.2]], dtype=float)           # Constant vector
n = len(b)
x = np.zeros(n, float)
print('Matrix A: \n {0}'.format(a))
print('Matrix B: \n {0}'.format(b))

# The simplest way to revise the code is add the following lines
if np.abs(a[0,0]) < np.abs(a[1,0]):
    a[[0, 1]] = a[[1, 0]]       # this is how you swap two rows
    b[[0, 1]] = b[[1, 0]]       # this is how you swap two elements
elif np.abs(a[0,0]) < np.abs(a[2,0]):
    a[[0, 2]] = a[[2, 0]]
    b[[0, 2]] = b[[2, 0]]
    
print('Matrix A after partial pivoting: \n {0}'.format(a))
print('Matrix B after partial pivoting: \n {0}'.format(b))

# forward elimination
for k in range(n):                                     # for matrix a, for each orig row k, starting at top
    for i in range(k+1,n):                             # get the next row i, first column element
        factor = a[i,k]/a[k,k]                         # and use it to get the factor
        for j in range(k,n):                           # then for the elements in each column of next row i,
            a[i,j] = a[i,j] - a[k,j]*factor            # calculate original values of next row i minus orig row k times factor 
        b[i] = b[i] - b[k]*factor                      # for matrix b, original value at next row i minus orig row k times factor

print('Augmented matrix')
print(np.concatenate((a,b), axis=1))                   # display result after forward elimination

# back substitution
x[n-1] = b[n-1]/a[n-1,n-1]                            # get last value of solution matrix
print(x[n-1])

for i in range(n-2,-1,-1):                             # 
    Sum = b[i]
    for j in range(i+1, n):
        Sum = Sum - a[i,j]*x[j]
    x[i] = Sum/a[i,i]
    
print(x)

Matrix A: 
 [[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
Matrix B: 
 [[106.8]
 [177.2]
 [279.2]]
Matrix A after partial pivoting: 
 [[ 64.   8.   1.]
 [ 25.   5.   1.]
 [144.  12.   1.]]
Matrix B after partial pivoting: 
 [[177.2]
 [106.8]
 [279.2]]
Augmented matrix
[[ 64.         8.         1.       177.2     ]
 [  0.         1.875      0.609375  37.58125 ]
 [  0.         0.         0.7        0.76    ]]
1.0857142857142725
[ 0.29047619 19.69047619  1.08571429]


In [5]:
X_py = np.linalg.solve(a,b)
print(X_py)
# Check if solution is correct
np.allclose(np.dot(a,X_py), b) # True if arrays are element-wuse equal

[[ 0.29047619]
 [19.69047619]
 [ 1.08571429]]


True